config {
  type: "table",
  schema: "silver_dev",
  name: "silver_gateway_customers",
  description: "Clientes no gateway de pagamento",
  tags: ["silver", "crm"]
}

SELECT
  customerId,
  userId,
  name,
  email,
  registry_code,
  status,
  address,
  phones,
  TIMESTAMP(created_at)  AS created_at,
  CURRENT_TIMESTAMP()    AS _transformed_at,
  '1.0.0'               AS _pipeline_version
FROM ${ref("gateway_customers")}
WHERE userId IS NOT NULL